### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by petr1231** [todvora/eet-client#38]
Hi, 
 your project stop work, because of certificate revocation.

Original Exception was java.security.cert.CertPathValidatorException: validity check failed
Caused by: java.security.cert.CertPathValidatorException: validity check failed
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Wed May 23 13:04:11 CEST 2018

Could you repair it asap please? I need it for my school project, just need working playground connection for now.

Many Thanks

**Comment by todvora** [comment]
Hi,
the problem is not in the library but rather in the EET playground itself. Responses from this environment are signed with an expired certificate (`NotAfter: Wed May 23 13:04:11 CEST 2018`). 

Here is one communication log I recorded today, capturing the request/response with this expired certificate: https://gist.github.com/todvora/2210e2d5ae146c47bf1ef12d64e36e53

There is currently nothing I can do with it, they have to renew the playground certificate. The certificate isn't part of this library, it's delivered with every XML response during the real communication mode (on the playground endpoint). I just enforce certificates validation.

Let's just hope they will fix it soon. For your school project, feel free to point your teacher to this issue. If you send messages int the `CommunicationMode.TEST`, they are not signed ([here's why](https://github.com/todvora/eet-client#for-playground)), there is no certificate to be validated and nothing to fail currently. Maybe you can present this mode. 

Best regards,
Tomas

**Comment by todvora** [comment]
They know about the problem and promised that it will be solved: https://twitter.com/SPCSS_sp/status/999385203817832448

**Comment by todvora** [comment]
Resolved, playground now uses fresh certificate valid till 2019:

![image](https://user-images.githubusercontent.com/4102775/40499624-cb66bff6-5f82-11e8-93a3-95142bed0f0c.png)

The actual certificate can be seen here: https://github.com/todvora/eet-client/blob/master/src/test/resources/keys/crls-demo-cert.pem (not used by the library, only for JUnit purposes).

Your real communication against the playground endpoint should be OK now.

Best regards,
Tomas
